export { default as HomePage } from "./Home";
export { default as Main } from "./Home/Main";
export { default as LogIn } from "./LogIn";
export { default as SignUp } from "./SignUp";
export { default as UploadDataset } from "./Upload";
export { default as Step1 } from "./Upload/Step1";
export { default as Step2 } from "./Upload/Step2";
export { default as Step3 } from "./Upload/Step3";
export { default as Step4 } from "./Upload/Step4";
